apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongoUn
  password: mongoSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connString: "Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPwPw;Database=auctions"
  rabbitUn: rabbitUn
  rabbitPw: rabbitSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  connString: mongodb://mongoUn:mongoSecretPwPw@mongo-clusterip
  rabbitUn: rabbitUn
  rabbitPw: rabbitSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-secret
type: Opaque
stringData:
  rabbitUn: rabbitUn
  rabbitPw: rabbitSecretPwPw
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: thisisevenmoresecretthanprevioussecrets
  clientSecret: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: bid-secret
type: Opaque
stringData:
  rabbitUn: rabbitUn
  rabbitPw: rabbitSecretPwPw
  connString: "mongodb://mongoUn:mongoSecretPwPw@mongo-clusterip"
